export enum IpcChannel {
  WindowNew = "window:new",
  WindowMinimize = "window:minimize",
  WindowMaximize = "window:maximize",
  WindowClose = "window:close",
  WindowTitleSet = "window:title-set",

  ImageSave = "image:save",
  AssetImport = "asset:import",
  AssetDelete = "asset:delete",
  AssetDeleteMany = "asset:delete-many",

  Navigate = "navigate",
  ToggleSidebar = "toggle-sidebar",

  SettingsGet = "settings:get",
  SettingsSet = "settings:set",
  SettingsChanged = "settings:changed",

  LayoutGet = "layout:get",
  LayoutSet = "layout:set",

  FileNew = "file:new",
  FileClose = "file:close",
  FileOpen = "file:open",
  FileOpened = "file:opened",
  FileSave = "file:save",
  FileSaveTrigger = "file:save-trigger",
  FileSaveAsTrigger = "file:save-as-trigger",
  ExportHtml = "export:html",
  ExportHtmlTrigger = "export:html-trigger",
  ExportPdf = "export:pdf",
  ExportPdfTrigger = "export:pdf-trigger",
  ExportPreview = "export:preview",

  ShellShowItemInFolder = "shell:show-item-in-folder",
  ShellOpenPath = "shell:open-path",

  RecentFilesGet = "recent-files:get",
  RecentFilesClear = "recent-files:clear",
  LastOpenedFileGet = "last-opened-file:get",

  WorkspaceOpen = "workspace:open",
  WorkspaceRead = "workspace:read",
  WorkspaceFileOpen = "workspace:file-open",

  FormatBold = "format:bold",
  FormatItalic = "format:italic",
  FormatStrikethrough = "format:strikethrough",
  FormatInlineCode = "format:inline-code",
  FormatMath = "format:math",
  FormatLink = "format:link",
  FormatImage = "format:image",
  FormatCodeBlock = "format:code-block",
  FormatBlockquote = "format:blockquote",
  FormatUnorderedList = "format:unordered-list",
  FormatOrderedList = "format:ordered-list",
  FormatTaskList = "format:task-list",
  FormatHorizontalRule = "format:horizontal-rule",
  FormatHeading1 = "format:heading-1",
  FormatHeading2 = "format:heading-2",
  FormatHeading3 = "format:heading-3",
  FormatHeading4 = "format:heading-4",
  FormatHeading5 = "format:heading-5",
  FormatHeading6 = "format:heading-6",
  FormatHeadingClear = "format:heading-clear",
}
